### ISSUE TITLE
use libmseed in release name

### ISSUE THREAD

**Issue by crotwell** [iris-edu/libmseed#29]
Current release is named 'v2.19.5.tar.gz' but once the file is downloaded, and a few weeks (or minutes depending on memory) pass, you have no idea what it is. Much better to name it
libmseed-2.19.5.tar.gz. Also nice if the untarred directory matches the filename. Currently the release untars to libmseed-2.19.5 which would match the above suggestion.

Seems like the standard is packagename-<tag>.tar.gz without a v in the tag.

**Comment by chad-iris** [comment]
The undecorated, i.e. without project, version of the name is generated by GitHub based on a tag.  The .tar.gz and .zip files are also automatically generated by GitHub based on a tag.  When the links are downloaded from GitHub a header is added to get the proper name, e.g.:
```
Content-Disposition: attachment; filename=libmseed-2.19.5.tar.gz
```
If you got something named "v2.19.5.tar.gz" it's because your HTTP client ignored this header.  If you are using curl try:
```
curl -JLO https://github.com/iris-edu/libmseed/archive/v2.19.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126    0   126    0     0    786      0 --:--:-- --:--:-- --:--:--   782
100  314k  100  314k    0     0  1005k      0 --:--:-- --:--:-- --:--:-- 1005k
curl: Saved to filename 'libmseed-2.19.5.tar.gz'
```
