### ISSUE TITLE
major API changes version 2 to 3: will existing code break?

### ISSUE THREAD

**Issue by alomax** [iris-edu/libmseed#39]
Hi Chad!

With the major API changes from version 2 to 3 of the library, will or can existing v2 code break if a data provider send miniseed data written with the v3 library?

This would be a severe problem for legacy, real-time and mission-critical systems that rely on libmseed.

**Comment by vlauciani** [comment]
Hi Anthony

You can get the last version 2 TAG:
```
$ git clone https://github.com/iris-edu/libmseed.git
$ cd libmseed
$ git checkout tags/v2.19.6
```

Valentino

**Comment by chad-iris** [comment]
Hi Anthony,

> With the major API changes from version 2 to 3 of the library, will or can existing v2 code break if a data provider send miniseed data written with the v3 library?

Any data written with the initial pre-release of the library is in the new format which is unreadable by the previous version of the library.  I've added a note to the release page to highlight this.

> This would be a severe problem for legacy, real-time and mission-critical systems that rely on libmseed.

I anticipate adding the ability for the library to write miniSEED 2 in the future, this would allow applications to update to the latest release if desired.  Until then applications that _must_ generate miniSEED 2, due to downstream processing, etc., should not be updated.  As @vlauciani helpfully points out, version 2 is still here and no plans for it to go away.

Somewhat related, I plan on updating the various pieces of data exchange software I maintain to handle both formats seamlessly.  Users of this software ecosystem should be able to chose when they want to start using the new format at their leisure.  It will take time to percolate though various systems, but it is both prudent and expected with a transition of data format.

**Comment by alomax** [comment]
Hi Chad,

Thanks for the details.  My main concern is not an isolated software ecosystem, but the larger data-exchange universe of earthquake seismology: 

Consider existing software using v2 which is regularly and automatically collecting miniseed from an arbitrary set of SeedLink servers or FDSN services.  If some of those servers/services are changed to v3, would the existing v2 mseed collecting software still seamlessly collect miniseed data and be able to decode this miniseed?

**Comment by chad-iris** [comment]
>  If some of those servers/services are changed to v3, would the existing v2 mseed collecting software still seamlessly collect miniseed data and be able to decode this miniseed?

No, not until they are updated to handle it as well.  So it goes with a transition in format.  It will not be the "larger data-exhange universe" all at once, it will start with smaller ecosystems and grow as needed from there.

Perhaps some context is missing: over the last 3 years we (with collaborators) have developed a "next generation miniSEED" format, which we plan to submit to the FDSN as a proposal that fulfills the requirements agreed and posted here:
http://www.fdsn.org/message-center/thread/514/#m-944
https://docs.google.com/document/d/1ymAe9v1rUuucpY7ai5ilKsD7V1ejwt6GxQQmJ5IevDI/edit

This pre-release of the library is one step in many of providing a software foundation, initially for readers of miniSEED, that is agnostic to which variation of miniSEED is being used.
