### ISSUE TITLE
mstl3_pack and mstl3_write with 'i' and 'a' encodings

### ISSUE THREAD

**Issue by dsentinel** [iris-edu/libmseed#56]
With a  `MS3TraceList` with segments of both waveform `encoding == 'i'` and ASCII log files `encoding == 'a'` 
I would like to `mstl3_write()` to a file with 'a' as ASCII and 'i' as STEIM2, However `...write()` and `...pack()` require and encoding and will not write the other.

Is there a simple way to do this without traversing the segments myself?
Or a different approach altogether?

**Comment by chad-iris** [comment]
Yeah, that was a non-useful limitation.  Fixed in v3.0.5:
https://github.com/iris-edu/libmseed/releases/tag/v3.0.5

Now, when packing a trace list, the encoding is only used for integer data.  Text (ASCII) and floating point data types are encoded in the only encoding that supports them.

Thanks for pointing this out @dsentinel

**Comment by dsentinel** [comment]
Sweet! thanks, Chad!
